grafis/urls.py
from django.urls import path

from .views import index, faq, program_studi, galeri, pendaftaran_online, program_lainnya

urlpatterns = [
    path('', index, name="index"),
    path('faq', faq, name="faq"),
    path('program_studi', program_studi, name='program_studi'),
    path('galeri', galeri, name='galeri'),
    path('pendaftaran_online', pendaftaran_online, name='pendaftaran_online'),
    path('program_lainnya', program_lainnya, name='program_lainnya')
]

interstudi_id/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing_page.urls')),
    path('fashion/', include('fashion.urls')),
    path('grafis/', include('grafis.urls')),
    path('sekretaris/', include('sekretaris.urls')),
    path('public_relations/', include('public_relations.urls')),
]

public_relations/urls.py
from django.urls import path

from .views import index,programlainnya,pendaftaranonline,hubungikami,gallery,biayastudi

app_name = "public_relations"

urlpatterns = [
    path('', index, name='index'),
    path('programlainnya', programlainnya, name="programlainnya"),
    path('pendaftaranonline', pendaftaranonline, name="pendaftaranonline"),
    path('hubungikami', hubungikami, name="hubungikami"),
    path('gallery', gallery, name="gallery"),
    path('biayastudi', biayastudi, name="biayastudi"),
]

public_relations/models.py
from django.db import models

# Create your models here.

public_relations/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
  return render(request, 'index_pr.html')

def programlainnya(request):
  program_lainnyas = {
    'sekretaris': {
      'title': 'Interstudi Sekretaris ',
      'desc': 'Menghasilkan lulusan sekretaris yang dapat melaksanakan tugas-tugas kesekretarisan atau administrasi perkantoran secara profesional, yang memiliki keterampilan berkomunikasi dan beradaptasi di lingkungan kerja, keterampilan komputer dan internet, memiliki pemahaman tentang manajemen, serta memiliki kepribadian dan berperilaku yang baik sesuai etika profesi.'
    },
    'grafis': {
      'title': 'Interstudi Grafis',
      'desc': 'Desain grafis adalah suatu bentuk komunikasi visual yang menggunakan gambar untuk menyampaikan informasi atau pesan seefektif mungkin. Dalam disain grafis, teks juga dianggap gambar karena merupakan hasil abstraksi simbol-simbol yang bisa dibunyikan, disain grafis diterapkan dalam disain komunikasi dan fine art.'
    },
    'interior': {
      'title': 'Interstudi Interior',
      'desc': 'Desain interior adalah Ilmu yang mempelajari perancangan suatu karya seni yang ada di dalam suatu bangunan dan digunakan untuk memecahkan masalah manusia. Salah satu bidang studi keilmuan yang didasarkan pada ilmu desain.'
    },
    'public_relations': {
      'title': 'Interstudi Public Relations',
      'desc': 'Public Relations adalah suatu proses yang berkesinambungan dari usaha manajemen untuk memperoleh good will dan pengertian dari publik pada umumnya, termasuk stake holder internal.'
    },
    'broadcasting': {
      'title': 'Interstudi Broadcasting',
      'desc': 'Pendidikan broadcasting memberikan pengajaran, pedidikan dan pelatihan kepada siswa untuk memasuki dunia lapangan kerja yang sesungguhnya di bidang penyiaran baik radio maupun televisi. Bahkan konsentrasi ini sangat diminati oleh mereka yang berjiwa kreatif di bidang audio visual.'
    },
    'language_center': {
      'title': 'Interstudi Language Center',
      'desc': 'Memiliki kemampuan berbahasa asing menjadi sangat penting, dalam mengantisipasi era globalisasi. Dengan kemampuan berbahasa asing yang baik, sangat mendukung berbagai profesi yang ada. Menyadari hal ini, InterStudi mengembangkan program studi bahasa.'
    },
    'bursa_kerja': {
      'title': 'Interstudi Bursa Kerja',
      'desc': 'Bursa Kerja InterStudi berdiri tahun 2000, menjadi wadah guna menjembatani para alumni InterStudi dengan perusahaan untuk memasuki dunia kerja. Bursa kerja ini sebagai salah satu wadah resmi guna mengaspirasi dan mengevaluasi seberapa banyak jumlah lulusan InterStudi yang terserap oleh perusahaan pencari kerja.'
    },
    'short_course':{
      'title': 'Interstudi Short Course',
      'desc': 'Program Short Course InterStudi di rancang bagi peserta yang ingin menambah wawasan namun memiliki waktu yang terbatas. Dengan lama belajar 2-3 hari, para peserta diharapkan mendapat pemahaman mengenai materi-materi yang sesuai dengan kebutuhannya.'
    }
  }
  return render(request, 'programlainnya.html', {"program_lainnya": program_lainnyas})  


def pendaftaranonline(request):
  return render(request, 'pendaftaranonline_pr.html') 

def hubungikami(request):
  return render(request, 'hubungikami.html') 

def gallery(request):
  return render(request, 'gallery.html') 

def biayastudi(request):
  return render(request, 'biayastudi.html') 

public_relations/templates/base_pr.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Interstudi Fashion</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <link rel="icon" href="{% static 'img/logo_interstudi.png' %}" />

    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="{% static 'css/index_pr.css' %}" />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg fixed-top py-3 navbar-light mx-auto">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mx-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'public_relations:index' %}"
              >Home <span class="sr-only">(current)</span></a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'public_relations:biayastudi' %}">Program Studi</a>
          </li>
          {% comment %} <li class="nav-item dropdown">
            <a
              class="nav-link dropdown-toggle"
              href="#"
              id="navbarDropdown"
              role="button"
              data-toggle="dropdown"
              aria-haspopup="true"
              aria-expanded="false"
            >
              Event
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Interstudi Nite</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Seminar</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Kegiatan Belajar</a>
            </div>
          </li> {% endcomment %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'public_relations:gallery' %}">Galeri</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'public_relations:pendaftaranonline' %}">Pendaftaran Online</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'public_relations:hubungikami' %}">Hubungi Kami</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'public_relations:programlainnya' %}">Program Lainnya</a>
          </li>
        </ul>
      </div>
    </nav>

    {% block content %} {% endblock %}

    <footer
      class="page-footer font-small mdb-color lighten-3 pt-4 footer-index"
    >
      <!-- Footer Links -->
      <div
        class="container text-center text-md-left"
        style="margin-bottom: 0px"
      >
        <!-- Grid row -->
        <div class="row">
          <!-- Grid column -->
          <div class="col-md-4 col-lg-3 mr-auto my-md-4 my-0 mt-4 mb-1">
            <!-- Content -->
            <img
              src="{% static 'img/logo_interstudi.png' %}"
              style="width: 100px"
              alt="halo halo bandung"
              id="iconFooter"
            />
          </div>
          <!-- Grid column -->

          <hr class="clearfix w-100 d-md-none" />

          <!-- Grid column -->
          <div class="col-md-2 col-lg-2 mx-auto my-md-4 my-0 mt-4 mb-1">
            <!-- Links -->
            <h5 class="font-weight-bold mb-4">Hubungi Kami</h5>

            <ul class="list-unstyled listFooter">
              <li>
                <p>Jl. Bulungan I No. 6</p>
              </li>
              <li>
                <p>Kebayoran Baru</p>
              </li>
              <li>
                <p>Jakarta Selatan</p>
              </li>
              <li>
                <p>Tlp : (021) 7250437</p>
              </li>
              <li>
                <p>Fax : (021)</p>
              </li>
            </ul>
          </div>
          <!-- Grid column -->

          <hr class="clearfix w-100 d-md-none" />

          <!-- Grid column -->
          <div class="col-md-4 col-lg-3 mx-auto my-md-4 my-0 mt-4 mb-1">
            <!-- Contact details -->
            <h5 class="font-weight-bold mb-4">Jam Operasional</h5>

            <ul class="list-unstyled listFooter">
              <li>
                <p>Senin s/d Jumat</p>
              </li>
              <li>
                <p>Pukul 8.30am-19.30pm</p>
              </li>
              <li>
                <p>Sabtu</p>
              </li>
              <li>
                <p>Libur</p>
              </li>
            </ul>
          </div>
          <!-- Grid column -->

          <hr class="clearfix w-100 d-md-none" />

          <!-- Grid column -->
          <div class="col-md-2 col-lg-2 text-center mx-auto my-4">
            <!-- Social buttons -->
            <h5 class="font-weight-bold mb-4">Ikuti Kami</h5>

            <!-- Instagram -->
            <a type="button" class="btn-floating btn-instagram">
              <a href="https://www.instagram.com/interstudi/" style="text-decoration: none; border: none; color: white; font-size: 25px;">
                <i class="fa fa-instagram"></i>
              </a>
            </a>
            <a type="button" class="btn-floating btn-instagram">
              <a href="https://www.facebook.com/interstudieducation/" style="text-decoration: none; border: none; color: white; font-size: 25px;">
                <i class="fa fa-facebook"></i>
              </a>
            </a>
            <a type="button" class="btn-floating btn-instagram">
              <a href="https://twitter.com/interstudi" style="text-decoration: none; border: none; color: white; font-size: 25px;">
                <i class="fa fa-twitter"></i>
              </a>
            </a>
          </div>
          <!-- Grid column -->
        </div>
        <!-- Grid row -->
      </div>
      <!-- Footer Links -->
    </footer>

    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <script>
      const isMobile = navigator.userAgentData.mobile;

      console.log(isMobile);

      if (isMobile) {
        $(".navbar").addClass("colored");
        $(".nav-link").addClass("colored-link");
      }

      $(function () {
        $(window).on("scroll", function () {
          if (!isMobile) {
            if ($(window).scrollTop() > 10) {
              $(".navbar").addClass("colored");
              $(".nav-link").addClass("colored-link");
            } else {
              $(".navbar").removeClass("colored");
              $(".nav-link").removeClass("colored-link");
            }
          }
        });
      });
    </script>
  </body>
</html>

public_relations/templates/biayastudi.html
{% extends 'base_pr.html' %} {% load static %} {% block content %}

<link rel="stylesheet" href="{% static 'css/biayastudi.css' %}" />

<div class="page-biayastudi">
  <div class="main-div-biayastudi"></div>
  <div class="pembatas-main"></div>
  <h1 class="title-biayastudi">Biaya Studi</h1>

  <div class="row">
    <div class="col-lg-4 center">
      <div class="card-biayastudi">
        <div class="kontenkuning">
          <h1 class="title-card-harga">Diploma in Public</h1>
          <h1 class="title-card-harga">Relations</h1>
          <span class="detailhargadiskon"><s>Rp. 8.750.000</s> </span>
          <h1 class="title-detailhargadiskona">Potongan Biaya 35%</h1>
          <div class="detailharga">
            <p class="sub-detailhargadiskon">Rp.5.6500.00,-</p>
          </div>
          <div class="bungkus-small-text">
            <p class="small-text-infopembayaran">Pembayaran Tunai</p>
            <p class="small-text-infopembayaran">Program 1 Tahun</p>
            <p class="small-text-infopembayaran">Angkatan 76</p>
          </div>
        </div>
        <div class="kontenputih">
          <div class="desc-angsuran">
            <p>Biaya Angsuran 3x</p>
            <p>Rp.8.750.000</p>
          </div>
          <hr class="garis" />
          <div class="desc-angsuran">
            <p>Pembayaran 1 :</p>
            <p>Rp.4.375.000</p>
          </div>
          <hr class="garis" />
          <div class="desc-angsuran">
            <p>Pembayaran 2 :</p>
            <p>Rp.2.625.000</p>
          </div>
          <hr class="garis" />
          <div class="desc-angsuran">
            <p>Pembayaran 3 :</p>
            <p>Rp.1.725.000</p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-4 center">
      <div class="card-biayastudi">
        <div class="kontenkuning">
          <h1 class="title-card-harga">Certificate in</h1>
          <h1 class="title-card-harga">Public Relations</h1>
          <span class="detailhargadiskon"><s>Rp. 6.550.000</s> </span>
          <h1 class="title-detailhargadiskona">Potongan Biaya 35%</h1>
          <div class="detailharga">
            <p class="sub-detailhargadiskon">Rp.4.250.00,-</p>
          </div>
          <div class="bungkus-small-text">
            <p class="small-text-infopembayaran">Program 6 bulan</p>
            <p class="small-text-infopembayaran">Angkatan 106</p>
          </div>
        </div>
        <div class="kontenputih">
          <div class="desc-angsuran">
            <p>Biaya Angsuran 2x</p>
            <p>Rp.6.550.000</p>
          </div>
          <hr class="garis" />
          <div class="desc-angsuran">
            <p>Pembayaran 1 :</p>
            <p>Rp.3.950.000</p>
          </div>
          <hr class="garis" />
          <div class="desc-angsuran">
            <p>Pembayaran 2 :</p>
            <p>Rp.2.600.000</p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-4 center">
      <div class="card-biayastudi">
        <div class="kontenkuning">
          <h1 class="title-card-harga">Program 3 Hari</h1>
          <h1 class="title-card-harga">Public Relations</h1>
          <span class="detailhargadiskon"><s>Rp. 2.250.000</s> </span>
          <h1 class="title-detailhargadiskona">Harga Early Bid</h1>
          <div class="detailharga">
            <p class="sub-detailhargadiskon">Rp.4.250.00,-</p>
          </div>
          <div class="bungkus-small-text">
            <p class="small-text-infopembayaran">- PROGRAM 3 HARI -</p>
          </div>
        </div>
        <div class="kontenputih">
          <div class="desc-angsuran">
            <p><b>Lama Studi:</b></p>
            <p>3 Hari Fullday</p>
            <p>08.30 s/d 16.30 wib</p>
            <p>jl. Bulungan</p>
          </div>
          <hr class="garis" />
          <div class="desc-angsuran">
            <p><b>Pembayaran 1 :</b></p>
            <p>Biaya sudah termasuk course</p>
            <p>material, coffe break, lunch dan</p>
            <p>certificate</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

public_relations/templates/gallery.html
{% extends 'base_pr.html' %} {% load static %} {% block content %}

<link rel="stylesheet" href="{% static 'css/gallery.css' %}" />

<div class="page-gallery">
  <div class="main-div-gallery"></div>
  <div class="pembatas-main"></div>
  <h1 class="title-gallery">Gallery</h1>

  <div class="row">
    <div class="col-lg-6 center">
      <div class="card-img">
        <img
          class="img-style-gallery"
          src="{% static 'img/gallery-1.png' %}"
          alt=""
        />
        <p class="text-desc-gallery">Interstudi Camp</p>
      </div>
    </div>
    <div class="col-lg-6 center">
      <div class="card-img">
        <img
          class="img-style-gallery"
          src="{% static 'img/gallery-2.png' %}"
          alt=""
        />
        <p class="text-desc-gallery">Table Manner</p>
      </div>
    </div>
    <div class="col-lg-6 center">
      <div class="card-img">
        <img
          class="img-style-gallery"
          src="{% static 'img/gallery-3.png' %}"
          alt=""
        />
        <p class="text-desc-gallery">Kunjungan Studi</p>
      </div>
    </div>
    <div class="col-lg-6 center">
      <div class="card-img">
        <img
          class="img-style-gallery"
          src="{% static 'img/gallery-4.png' %}"
          alt=""
        />
        <p class="text-desc-gallery">Seminar Interstudi</p>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

public_relations/templates/hubungikami.html
{% extends 'base_pr.html' %} {% load static %} {% block content %}

<link rel="stylesheet" href="{% static 'css/hubungikami.css' %}" />

<div class="page-faq">
  <div class="main-div-pengajar"></div>
  <div class="pembatas-main"></div>
  <h1 class="title-pendaftaran">Hubungi Kami</h1>
  <h1 class="title-pendaftaran">InterStudi Public Relations</h1>
  <div class="card-faq">
    <div class="faq-form">
      <input type="text" name="" id="" placeholder="Nama Lengkap" />
      <br /><br />
      <input type="text" name="" id="" placeholder="Email" />
      <br /><br />
      <input type="text" name="" id="" placeholder="Judul" />
      <br /><br />
      <textarea rows="5" placeholder="Pertanyaan"></textarea>
      <br /><br />
    </div>
  </div>
  <div class="center">
    <button type="submit" class="faq-button">SUBMIT</button>
  </div>
</div>

{% endblock content %}

public_relations/templates/index_pr.html
{% extends 'base_pr.html' %} {% load static %} {% block content %}

<div class="indexpage" style="background-color: #fafafa; padding-bottom: 100px">
  <!-- section 1  -->
  <div class="main-div">
    <div class="title-div">
      <div class="title-inner">
        <div class="konten-main">
          <div class="title-design">
            <h1 class="content-title-design">SCHOOL OF</h1>
            <h1 class="content-title-design">PUBLIC RELATIONS</h1>
          </div>

          <p class="detail-main-div">
            Public Relations adalah proses yang berkesinambungan dari usaha
            manajemen untuk memperoleh good will dan pengertian dari publik pada
            umumnya, termasuk stake holder internal.
          </p>
          <div class="container">
            <div class="row">
              <div class="col div-buttonawal">
                <a href="#konten">
                  <button class="button button3" href="#about">
                    Daftar
                  </button></a
                >
              </div>
            </div>
          </div>
        </div>

        <!-- <a class="a-explore" href="#"
          ><div class="button-explore">EXPLORE</div></a
        > -->
      </div>
    </div>
  </div>
  <!-- section 1  -->

  <section id="konten" class="section-padding">
    <!-- section 2  -->
    <div class="container tujuan-utama">
      <p class="text-tugasutama">
        Tugas utama seorang public relations officer diantaranya mewakili
        perusahaan tempat anda bekerja untuk mewujudkan hubungan harmonis denan
        para klien, menjaga nama baik perusahaan, serta menyampaikan
        gagasan-gagasan yang menarik dan benar agar reputasi perusahaan tetap
        terjaga di mata masyarakat.
      </p>
      <div class="garis-orange"></div>

      <div class="row">
        <div class="col-lg-4 card-col-total">
          <div class="card-jumlah-card">
            <div class="konten-card">
              <p class="text-jenis-program">Program 1 Tahun</p>
              <p class="text-jumlah-total-program">5625</p>
              <p class="text-jenis-program">Total Siswa</p>
              <div class="garis-orange-card"></div>
              <p class="text-jenis-program">75 Angkatan</p>
            </div>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="card-jumlah-card">
            <div class="konten-card">
              <p class="text-jenis-program">Program 6 bulan</p>
              <p class="text-jumlah-total-program">4160</p>
              <p class="text-jenis-program">Total Siswa</p>
              <div class="garis-orange-card"></div>
              <p class="text-jenis-program">104 Angkatan</p>
            </div>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="card-jumlah-card">
            <div class="konten-card">
              <p class="text-jenis-program">Program 3 hari</p>
              <p class="text-jumlah-total-program">5625</p>
              <p class="text-jenis-program">Total Siswa</p>
              <div class="garis-orange-card"></div>
              <p class="text-jenis-program">62 Angkatan</p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- section 3  -->
    <div id="wrapper">
      <div id="c1"></div>
      <div id="c2">
        <div class="konten-profile">
          <div class="text-div-profile">
            <p class="title-Profile">Profile</p>
            <p class="text-title-prof">
              Nama InterStudi makna berbagai bidang studi dan pelatihan.
            </p>
          </div>
          <div class="text-div-moto">
            <p class="subtittle-profile moto">Moto</p>
            <p class="tex-subprof">
              Keunggulan untuk menghasilkan yang terbaik
            </p>
          </div>
          <div class="text-div-visi">
            <p class="subtittle-profile visi">Visi</p>
            <p class="tex-subprof">
              Menjadikan lembaga pelatihan terkemuka, konsisten dalam
              meningkatkan dan pengembangan kualitas sumber daya manusia sesuai
              kebutuhan global, menjadi yang terbaik melalui pengelolaan
              profesional.
            </p>
          </div>
          <div class="text-div-misi">
            <p class="subtittle-profile misi">Misi</p>
            <p class="tex-subprof">
              Menyelenggarakan berbagai bidang pendidikan dan pelatihan guna
              meningkatkan kualitas sumber daya manusia untuk memenuhi berbagai
              kesempatan kerja.
            </p>
          </div>
        </div>
      </div>
    </div>
    <!-- section 3  -->

    <div class="daftar-harga">
      <div class="materi-tittle-inner">
        <div class="title-materi-design">
          <h1 class="content-materi-design">Daftar Harga</h1>
        </div>
      </div>

      <div class="container">
        <div class="row">
          <div class="col-lg-6 col-md-6 card-harga">
            <div class="column-card-harga">
              <h1 class="title-card-harga">Harga Online</h1>
              <span class="detailhargadiskon"><s>Rp. 11.550.000</s> </span>
              <p>Potongan biaya 35%</p>
              <br />

              <p>Khusus harga di tahun 2021</p>
              <p class="fix-harga">Rp.7.500.000</p>
              <div class="jenis-pembayaran">
                <p class="isi-jenis-tunai">Pembayaran Tunai</p>
                <p class="isi-jenis-tunai-2">Program 6 Bulan</p>
              </div>

              <div class="garis-bayar">
                <hr class="garis" />
                <p class="bayar-angsuran">Bayar Dengan Angsuran 3x</p>
                <hr class="garis" />
              </div>

              <p class="total-bayar">-Rp. 11.300.00,00</p>

              <div class="detail-angsuran">
                <p>Angsuran 1.Rp.5.855.000</p>
                <p>Angsuran 2.Rp.3.525.000</p>
                <p>Angsuran 3.Rp.2.250.000</p>
              </div>
            </div>
          </div>
          <div class="col-lg-6 col-md-6 card-harga">
            <div class="column-card-harga">
              <h1 class="title-card-harga">Harga Online</h1>
              <span class="detailhargadiskon"><s>Rp. 11.750.000</s> </span>
              <p>Potongan biaya 35%</p>
              <br />

              <p>Khusus harga di tahun 2021</p>
              <p class="fix-harga">Rp.7.600.000</p>
              <div class="jenis-pembayaran">
                <p class="isi-jenis-tunai">Pembayaran Tunai</p>
                <p class="isi-jenis-tunai-2">Program 6 Bulan</p>
              </div>

              <div class="garis-bayar">
                <hr class="garis" />
                <p class="bayar-angsuran">Bayar Dengan Angsuran 3x</p>
                <hr class="garis" />
              </div>

              <p class="total-bayar">-Rp. 11.750.00,00</p>

              <div class="detail-angsuran">
                <p>Angsuran 1.Rp.5.855.000</p>
                <p>Angsuran 2.Rp.3.525.000</p>
                <p>Angsuran 3.Rp.2.350.000</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="maps">
      <iframe
        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d31728.50632921006!2d106.797831358722!3d-6.255392560214115!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e69f16ae11eebb1%3A0x77bb713e6c8e9d09!2sInterStudi%20Bulungan!5e0!3m2!1sen!2sid!4v1628184336716!5m2!1sen!2sid"
        class="map-interstudi"
        style="border: 0"
        allowfullscreen=""
        loading="lazy"
      ></iframe>
    </div>
  </section>
</div>

{% endblock content %}

public_relations/templates/pendaftaranonline_pr.html
{% extends 'base_pr.html' %} {% load static %} {% block content %}

<link rel="stylesheet" href="{% static 'css/pendaftaranonline_pr.css' %}" />

<div class="page-faq">
  <div class="main-div-pengajar"></div>
  <div class="pembatas-main"></div>
  <h1 class="title-pendaftaran">Pendaftaran Online</h1>
  <div class="card-faq">
    <div class="faq-form">
      <input type="text" name="" id="" placeholder="Program Studi" />
      <br /><br />
      <input
        placeholder="Jadwal Studi"
        class="textbox-n"
        type="text"
        onfocus="(this.type='date')"
        id="date"
      />
      <br /><br />
      <input
        placeholder="Tanggal Lahir"
        onfocus="(this.type='time')"
        id="appt"
        name="appt"
        min="09:00"
        max="18:00"
        required
      />
      <br /><br />
      <input type="text" name="" id="" placeholder="Biaya Studi" />
      <br /><br />
      <input type="text" name="" id="" placeholder="Nama Studi" />
      <br /><br />
      <textarea rows="3" placeholder="Alamat Lengkap"></textarea>
      <br /><br />
      <input
        placeholder="Tanggal Lahir"
        class="textbox-n"
        type="text"
        onfocus="(this.type='date')"
        id="date"
      />
      <br /><br />
      <input type="text" name="" id="" placeholder="Email" />
      <br /><br />
      <select>
        <option value="" disabled selected>Jenis Kelamin</option>
        <option value="Laki">Laki</option>
        <option value="Perempuan">Perempuan</option>
      </select>
      <br /><br />
    </div>
  </div>
  <div class="center">
    <button type="submit" class="faq-button">SUBMIT</button>
  </div>
</div>

{% endblock content %}